version: "3.7"

services:
  db-tipbot:
    network_mode: host
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
    volumes:
      - /var/opt/mssql-${COMPOSE_PROJECT_NAME}:/var/opt/mssql 
  qt-tipbot:
    network_mode: host    
    build: 
      context: ./wallet-qt
      args:
        - walletRepo
        - walletDaemon
    volumes:
      - ${walletHostDir}:${walletContainerDir}
  tipbot:
    network_mode: host
    build: 
      context: ..
      dockerfile: Docker/tipbot/Dockerfile
    environment:
      - daemonUrl=${daemonUrl}
      - rpcUsername=${rpcUsername}
      - rpcPassword=${rpcPassword}
      - walletPassword=${walletPassword}
      - token=${token}
      - connectionString=${connectionString}
      - ticker=${ticker}
      - botprefix=${botprefix}
      - supportUsername=${supportUsername}
      - supportDiscriminator=${supportDiscriminator}
    depends_on: 
      - db-tipbot
      - qt-tipbot
volumes:
  mssql-tipbot:
